### ISSUE TITLE
Ip addressing

### ISSUE THREAD

**Issue by HarshRangwala** [SochInc/Self-Driving-RC-Car#11]
Hi I am having issues with assigning the ip addresses. Could you please help me how do I get correct ip addresses?
For instance what ip should I use in ```control.py```. I have tried ifconfig (inet:192.168.0.31, local : 127.0.0.1 and local host address: 127.0.1.1) Please reply, I have a deadline. Its urgent.
Thank you!!

**Comment by HarshRangwala** [comment]
I am following this sequence to run the file: python control.py >> python camstream.py [in different terminals] then python manual.py
Its correct? Please respond! 
Thank you.

**Comment by l3lackcurtains** [comment]
Use the IP address of the devices (Raspberry pi and Computer) assigned by the router. (format of 192.168. . .)
The sequence to run the file is: camstream.py and manual_drive.py in training mode.
Similarly, camstream.py and run.py on autonomous mode.

**Comment by HarshRangwala** [comment]
Okay. Thank you for replying, @l3lackcurtains . I am using raspberry pi's address for Flask and my computers IP as a server. I can drive properly.
**1.** However I am a little confused when it comes to Forward_right() ad Forward_left(). Could you or anyone, please look up the code attached below and let me know what I am doing wrong. In order to go forward right, I have to first press up key and the left or right key but I cant do it in parallel. I think this might slow down my car on turns. please let me know the solution.

```
from flask import Flask, jsonify, request, Response
import RPi.GPIO as GPIO
import time
import json
import configuration

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

BACK_MOTOR_DATA_ONE = configuration.BACK_MOTOR_DATA_ONE
BACK_MOTOR_DATA_TWO = configuration.BACK_MOTOR_DATA_TWO
BACK_MOTOR_ENABLE_PIN = configuration.BACK_MOTOR_ENABLE_PIN
FRONT_MOTOR_DATA_ONE = configuration.FRONT_MOTOR_DATA_ONE
FRONT_MOTOR_DATA_TWO = configuration.FRONT_MOTOR_DATA_TWO
PWM_FREQUENCY = configuration.PWM_FREQUENCY

GPIO.setup(BACK_MOTOR_DATA_ONE,GPIO.OUT)
GPIO.setup(BACK_MOTOR_DATA_TWO,GPIO.OUT)
GPIO.setup(FRONT_MOTOR_DATA_ONE,GPIO.OUT)
GPIO.setup(FRONT_MOTOR_DATA_TWO,GPIO.OUT)


GPIO.output(BACK_MOTOR_DATA_ONE,GPIO.LOW)
GPIO.output(BACK_MOTOR_DATA_TWO,GPIO.LOW)
GPIO.output(FRONT_MOTOR_DATA_ONE,GPIO.LOW)
GPIO.output(FRONT_MOTOR_DATA_TWO,GPIO.LOW)

'''
app = Flask(__name__) Special var in python that is just the name of the module. This helps Flask to know
                      where to look for template and static files. 
                        
'''
app = Flask(__name__)                 
@app.route('/messages', methods = ['POST']) # rout are used for the webpage to have additional functionality.
def api_message():
        data = request.args.get('data')
        control(data)

def control(key):
        print(key)
        if key == 's': 
                print ("Backward")
                GPIO.output(BACK_MOTOR_DATA_ONE, False)
                GPIO.output(BACK_MOTOR_DATA_TWO, True)
                            
        elif key == 'w':
                print ("forward")
                GPIO.output(BACK_MOTOR_DATA_ONE, True)
                GPIO.output(BACK_MOTOR_DATA_TWO, False)

        elif key == 'a':
                print ("Left")
                GPIO.output(FRONT_MOTOR_DATA_ONE, False)
                GPIO.output(FRONT_MOTOR_DATA_TWO, True)
        elif key == 'd':
                print ("Right")
                GPIO.output(FRONT_MOTOR_DATA_ONE, True)
                GPIO.output(FRONT_MOTOR_DATA_TWO, False)
        elif key == 'e':
                print ("Forward Left")
                GPIO.output(FRONT_MOTOR_DATA_ONE, False)
                GPIO.output(FRONT_MOTOR_DATA_TWO, True)
                GPIO.output(BACK_MOTOR_DATA_ONE, True)
                GPIO.output(BACK_MOTOR_DATA_TWO, False)
        elif key == 'q':
                print ("Forward Right")
                GPIO.output(FRONT_MOTOR_DATA_ONE, True)
                GPIO.output(FRONT_MOTOR_DATA_TWO, False)
                GPIO.output(BACK_MOTOR_DATA_ONE, True)
                GPIO.output(BACK_MOTOR_DATA_TWO, False)
                
        elif key == 'x':
                GPIO.output(BACK_MOTOR_DATA_ONE,GPIO.LOW)
                GPIO.output(BACK_MOTOR_DATA_TWO,GPIO.LOW)
                GPIO.output(FRONT_MOTOR_DATA_ONE,GPIO.LOW)
                GPIO.output(FRONT_MOTOR_DATA_TWO,GPIO.LOW)
        elif key == 'quit':
                quit()

if __name__ == '__main__':
    app.run(host='192.168.0.31', port=5000, debug=False) #debug = True
```
**2.**What does this error mean? It appears in the training stage. [I run camstream.py, control.py, manual_drive.py].
```
ConnectionError: HTTPConnectionPool(host='192.168.0.31', port=5000): Max retries exceeded with
 url: /messages?data=x (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object
 at 0x00000244EF484E08>: Failed to establish a new connection: [WinError 10060] A connection 
attempt failed because the connected party did not properly respond after a period of time, or 
established connection failed because connected host has failed to respond'))
```

**Please respond, I have to submit by the end of next month.**
Thank you in advance.
This is the RC car I am using.

![RCcar](https://user-images.githubusercontent.com/41195974/72822426-18fab300-3c98-11ea-800a-dc424d739ce2.jpeg)


**Please respond, I have to submit by the end of next month.**
Thank you in advance.

**Comment by l3lackcurtains** [comment]
That code won't apply in your case.

I had used a three-wheel RC car in my project but, you are using 4-wheel one.

Check your Raspberry Pi GPIO pins connection and write code according to it. I hope you can do it.

**Comment by HarshRangwala** [comment]
@l3lackcurtains But I am using 2 motors and I could implement all the directions the first time I ran.

**Comment by HarshRangwala** [comment]
@l3lackcurtains Are you saying the whole code wont apply or only the one with forward_right and forward_left??

**Comment by HarshRangwala** [comment]
@l3lackcurtains ??

**Comment by l3lackcurtains** [comment]
You need to change the code according to your GPIO configuration in Raspberry Pi.
