### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by HarshRangwala** [SochInc/Self-Driving-RC-Car#12]
After I run camstream.py and control.py on my raspi, manual_drive.py on my computer. The whole camera output "unfortunately stops" and I get this message:
```
    raise ConnectionError(e, request=request)

ConnectionError: HTTPConnectionPool(host='192.168.0.32', port=5000): Max retries exceeded with 
url: /messages?data=x (Caused by NewConnectionError('<urllib3.connection.HTTPConnection 
object at 0x00000157205CD148>: Failed to establish a new connection: [WinError 10060] A 
connection attempt failed because the connected party did not properly respond after a period of 
time, or established connection failed because connected host has failed to respond'))

```
 everything worked fine the first time
Please help.

In control.py I inserted my Pi's ip address, when I visit http://192.168.0.32:5000/ I get:

```
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

After puting this url,  http://192.168.0.32:5000/messages
I get
```
Method Not Allowed
The method is not allowed for the requested URL.
```
**Please help me understand. I am close to a deadline.**
Thank you in advanced.

**Comment by l3lackcurtains** [comment]
You need to run control.py in Raspberry Pi before you run manual_drive on the computer.

**Comment by HarshRangwala** [comment]
I am following the same pattern. As I mentioned 

> After I run camstream.py and control.py on my raspi, manual_drive.py on my computer. 


1st I run camstream.py and control.py AND THEN manual_drive. I still get this error.

**Comment by l3lackcurtains** [comment]
There is something wrong with the connection from raspberry pi to the computer.
Check it. I hope you can fix it.
