### ISSUE TITLE
Error when running manual_drive

### ISSUE THREAD

**Issue by zadahmed** [SochInc/Self-Driving-RC-Car#8]
Whenever i try to run manual_drive.py i always seem to get a broken pipe error. Could you help me through this.

**Comment by l3lackcurtains** [comment]
You need to edit the server(Raspberry Pi) address '192.168.1.101'.

https://github.com/SochInc/Self-Driving-RC-Car/blob/master/RaspberryPi/camstream.py
```python
client_socket.connect(('192.168.1.100',8000))
```

**Comment by l3lackcurtains** [comment]
You need to edit the Raspberry Pi address '192.168.1.106' and Computer Address '192.168.1.101' to your own.

**Comment by l3lackcurtains** [comment]
Also, make sure your local IP is not changed at a different time like when after restarting the router.
